feat(alert): Add alert rule for perccli
canonical/charm-prometheus-hardware-exporter pull request #10
Opened 2023-06-15 02:36 UTC by jneo8

- Add alert rule for perccli

2023-06-15 06:22 UTC, sudeephb reviewed
Added a few non-blocking comments.

2023-06-15 06:22 UTC, sudeephb commented on src/prometheus_alert_rules/perccli.yaml
> +        Cannot found PowerEdge RAID controller on this host machine.
Nitpick
```suggestion
        Cannot find PowerEdge RAID controller on this host machine.
```

2023-06-15 06:22 UTC, sudeephb commented on src/prometheus_alert_rules/perccli.yaml
> +      summary: PowerEdge RAID controller command not success.  (instance {{ $labels.instance }})
```suggestion
      summary: PowerEdge RAID controller command not successful.  (instance {{ $labels.instance }})
```

2023-06-15 06:22 UTC, sudeephb commented on src/prometheus_alert_rules/perccli.yaml
> +        Fail to get PowerEdge RAID controller information on controller {{ $labels.controller_id }}.
```suggestion
        Failed to get PowerEdge RAID controller information on controller {{ $labels.controller_id }}.
```

2023-06-15 06:22 UTC, sudeephb commented on src/prometheus_alert_rules/perccli.yaml
> +      summary: Failed to run perccli or not controller available. (instance {{ $labels.instance }})
```suggestion
      summary: Failed to run perccli or controller not available. (instance {{ $labels.instance }})
```

2023-06-15 06:37 UTC, sudeephb approved these changes
LGTM

2023-06-15 10:17 UTC, Pjack requested changes

2023-06-15 10:17 UTC, Pjack commented on src/prometheus_alert_rules/perccli.yaml
> +    expr: poweredgeraid_virtual_info{state != "Optl"} == 1
If there are 2 VD not in optimal, will it generate 2 alert? 
I will purpose to calculate how many virtual dirve not in optimal , when it is larget than 0, then send alert.

2023-06-15 10:39 UTC, Pjack requested changes

2023-06-15 10:39 UTC, Pjack commented on src/prometheus_alert_rules/perccli.yaml
> +    expr: poweredgeraid_virtual_info{state != "Optl"} == 1
BTW, we should be able to indiciate the identifier of virtual drive. So the COE doesn't need to exectue any command to find out which drive is broken. If my proposal cannot achieve that, it may be a bad idea.

We can also check if we can "consolidate" the alert messages from the alert manager level.

2023-06-15 10:39 UTC, Pjack commented on src/prometheus_alert_rules/perccli.yaml
> +      severity: critical
If that is a RAID, I think it's okay as "warning". 
We still have the backup in the 2nd storage if it is RAID1. For RAID5, we can also afford 1 disk failures. 

Is there any state that is really terrible (e.g. data may lost ) , so that we should set the severity as critical?

2023-06-16 06:21 UTC, jneo8 commented on src/prometheus_alert_rules/perccli.yaml
> +    expr: poweredgeraid_virtual_info{state != "Optl"} == 1
It should be >= 1.

The identifier of virtual drive is already in the labels.

2023-06-16 06:34 UTC, jneo8 commented on src/prometheus_alert_rules/perccli.yaml
> +      severity: critical
> Is there any state that is really terrible (e.g. data may lost ) , so that we should set the severity as critical?

There is no document to list down all the possible output for perccli. Currently we only raise alert if it's not Optl.

2023-06-16 07:24 UTC, Pjack commented on src/prometheus_alert_rules/perccli.yaml
> +    expr: poweredgeraid_virtual_info{state != "Optl"} == 1
Confuse now. In @chanchiwai-ray 's commit.  it's == 1.  Which is correct?
https://github.com/canonical/charm-prometheus-hardware-exporter/pull/9/files/215d9e74d3099ea229dce18319ad3e64948fa671

2023-06-16 09:28 UTC, jneo8 commented on src/prometheus_alert_rules/perccli.yaml
> +    expr: poweredgeraid_virtual_info{state != "Optl"} == 1
Sorry, I provide the wrong information.

It will generate 2 alerts. each alert for one virtual drive with different labels.
It somehow make sense because usually virtual drive won't broke in the same time. COE will need to handle that specific virtual drive.

2023-06-16 10:14 UTC, Pjack approved these changes
LGTM

2023-06-16 10:51 UTC, jneo8 commented
The functional test fail is not relate to this PR.

2023-06-16 10:51 UTC, merged