[WIP] Add exporter integration
canonical/charm-prometheus-hardware-exporter pull request #13
Opened 2023-06-19 10:12 UTC by chanchiwai-ray

2023-06-19 10:18 UTC, chanchiwai-ray commented
Please check the draft to see If you agree on this approach or not. In particular, should the exporter install and uninstall itself when `cos-agent` is joined and departed.

2023-06-20 02:04 UTC, jneo8 commented
> Please check the draft to see If you agree on this approach or not. In particular, should the exporter install and uninstall itself when `cos-agent` is joined and departed; and installing the exporter via github repo.

I only have one question: **If the relation is not exists. Do that make sense we have a exporter on the machine?**

The only possible purpose for me is for debug usage. But if we don't want to have a exporter installed on the machine when the relation not exists. Shouldn't we just remove the charm? I will say we can keep the options open.

My proposal is:

1. If the relation is not exists, we still have the exporter service.
2. We remove everything, resource and services,  when charm is being removed.
3. Because the remove part is a independent lib, we can choose to have that if someone persist to have it.

2023-06-20 02:23 UTC, chanchiwai-ray commented
> I only have one question: **If the relation is not exists. Do that make sense we have a exporter on the machine?**
> 
> The only possible purpose for me is for debug usage. But if we don't want to have a exporter installed on the machine when the relation not exists. Shouldn't we just remove the charm? I will say we can keep the options open.

I think both "Install when relation joined" (1) and "Install when the charm is installed" (2) make sense to me, but on a different angle: For (1) it's viewed from the actual usage the exporter; the exporter is actually used when there's `cos-agent` relation. For (2), just like you said, we can view the charm and exporter as a single entity, then we don't need the charm if we don't need the exporter. But both way are okay to me. Or we can have a mix of both (1) and (2)

- Install the config and service template for the exporter (but not start it) when the charm is installed; also resources..
- Start the service when the `cos-agent` relation is joined
- Stop the service when the `cos-agent` relation is departed
- Uninstall the config and service when the charm is removed, also resources..


> My proposal is:
> 
> 1. If the relation is not exists, we still have the exporter service.
> 2. We remove everything, resource and services,  when charm is being removed.
> 3. Because the remove part is a independent lib, we can choose to have that if someone persist to have it.

2023-06-20 02:54 UTC, jneo8 commented
> > I only have one question: **If the relation is not exists. Do that make sense we have a exporter on the machine?**
> > The only possible purpose for me is for debug usage. But if we don't want to have a exporter installed on the machine when the relation not exists. Shouldn't we just remove the charm? I will say we can keep the options open.
> 
> I think both "Install when relation joined" (1) and "Install when the charm is installed" (2) make sense to me, but on a different angle: For (1) it's viewed from the actual usage the exporter; the exporter is actually used when there's `cos-agent` relation. For (2), just like you said, we can view the charm and exporter as a single entity, then we don't need the charm if we don't need the exporter. But both way are okay to me. Or we can have a mix of both (1) and (2)
> 
> * Install the config and service template for the exporter (but not start it) when the charm is installed; also resources..
> * Start the service when the `cos-agent` relation is joined
> * Stop the service when the `cos-agent` relation is departed
> * Uninstall the config and service when the charm is removed, also resources..
> 
> > My proposal is:
> > 
> > 1. If the relation is not exists, we still have the exporter service.
> > 2. We remove everything, resource and services,  when charm is being removed.
> > 3. Because the remove part is a independent lib, we can choose to have that if someone persist to have it.

Start and stop make sense to me. @sudeephb How do you think?

2023-06-20 03:56 UTC, sudeephb commented
> > * Install the config and service template for the exporter (but not start it) when the charm is installed; also resources..
> > * Start the service when the `cos-agent` relation is joined
> > * Stop the service when the `cos-agent` relation is departed
> > * Uninstall the config and service when the charm is removed, also resources..

I agree with this. Having the exporter up when there's no cos-agent relation doesn't make sense. This way, we can also give a `blocked` status message saying the exporter is not running since there's no relation.

2023-06-20 08:37 UTC, jneo8 requested changes
Just some small nitpick.

2023-06-20 08:37 UTC, jneo8 commented on src/config.py
> +EXPORTER_CONFIG_PATH = f"/etc/{EXPORTER_NAME}-config.yaml"
**nitpick (non-blocking):** 

I prefer to have `Path` type for path variables.

2023-06-20 08:37 UTC, jneo8 commented on src/service.py
> +class Template:
**suggestion (blocking):** 

The naming of this class somehow not precise. Because it's not just for generate the template. Maybe we can change to some terms which relate to service?

2023-06-20 08:37 UTC, jneo8 commented on templates/hardware-exporter-config.yaml.j2
> +level: INFO
**nitpick (blocking):** 

Should the level follow the loglevel config?

2023-06-20 08:44 UTC, chanchiwai-ray commented on templates/hardware-exporter-config.yaml.j2
> +level: INFO
But we don't have log level config option for the charm. Or does it make sense to have it on the charm ?

2023-06-20 08:49 UTC, chanchiwai-ray commented on src/service.py
> +class Template:
Any suggestion?

2023-06-20 08:51 UTC, chanchiwai-ray commented on src/config.py
> +EXPORTER_CONFIG_PATH = f"/etc/{EXPORTER_NAME}-config.yaml"
DONE

2023-06-20 10:26 UTC, jneo8 commented on templates/hardware-exporter-config.yaml.j2
> +level: INFO
It's make sense to have that option on the charm. It will be helpful when debugging.

2023-06-21 04:07 UTC, chanchiwai-ray commented on templates/hardware-exporter-config.yaml.j2
> +level: INFO
DONE

2023-06-21 04:42 UTC, sudeephb commented on src/config.py
>  # EXPORTER_NAME = "prometheus-hardware-exporter"
Can we remove this line?

2023-06-21 04:42 UTC, sudeephb commented on src/service.py
> +class Template:
Maybe something like `ExporterTemplate` or `ExporterHelper` ?

2023-06-21 04:48 UTC, chanchiwai-ray commented on src/config.py
>  # EXPORTER_NAME = "prometheus-hardware-exporter"
Yes

2023-06-21 07:43 UTC, sudeephb commented on src/config.py
>  # Register every vendoer's tool here.
```suggestion
# Register every vendor's tool here.
```

2023-06-21 07:47 UTC, sudeephb commented on src/service.py
> +        if len(observe.intersection(change_set)) > 0:
I don't see any extra benefit of checking this when we are already checking if `exporter-log-level in change_set` and doing the operation below. Or am I missing something?

2023-06-21 07:47 UTC, sudeephb commented on src/service.py
> +            logger.error("Failed to uninstalled %s.", EXPORTER_NAME)
```suggestion
            logger.error("Failed to uninstall %s.", EXPORTER_NAME)
```

2023-06-21 09:36 UTC, sudeephb commented on src/charm.py
>          self.model.unit.status = ActiveStatus("Unit is ready")
Non-blocking. Since we're using this string `Unit is ready` twice, and may be used more times in the future, it may make sense to store it in a variable and use the variable everywhere. What do you think?

2023-06-21 09:37 UTC, sudeephb approved these changes

2023-06-21 11:52 UTC, jneo8 approved these changes

2023-06-22 14:25 UTC, rgildein commented
I still think that such a decision should be discussed, since we are using snap in all other charms and I would sad to see us break the consistency. I'm not saying that this is not a valid solution, maybe yes, but we need to properly consider it and probably apply it in other charms as well.

2023-06-26 01:58 UTC, chanchiwai-ray commented
@rgildein I understand your concerns. However, this solution is not coming out of no where and we had mentioned it in our [internal spec review](https://docs.google.com/document/d/1tGmFg-LCfSxIkAWoNZvtnb4DuvPomuEk-yqspLrkIwc/edit). We also pointed out that snap implementation might have unexpected blockers. But thanks for the comments and suggestions, I think we can still do better in communicating the final decision / change of direction.

2023-06-26 02:03 UTC, chanchiwai-ray commented on src/charm.py
>          self.model.unit.status = ActiveStatus("Unit is ready")
It was used in different function scope, maybe it's not of any benefit to create an attribute to store the string `Unit is ready`

2023-06-26 03:11 UTC, merged