Add alert rules for ssacli
canonical/charm-prometheus-hardware-exporter pull request #16
Opened 2023-06-23 05:07 UTC by sudeephb

2023-06-23 10:34 UTC, rgildein commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
Do we have metrics like this for single scrape?
```
ssacli_ld_info{..., status="OK"} = 1
ssacli_ld_info{..., status="ERROR"} = 0
```

2023-06-23 11:37 UTC, sudeephb commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
The metric value will always be 1, it's an [info metric ](https://github.com/prometheus/client_python/blob/master/prometheus_client/metrics_core.py#L338). We do have metric for status = "OK", the outputs(and metrics from those) [here](https://github.com/sudeephb/prometheus-hardware-exporter/blob/ssacli_collector/tests/unit/test_resources/ssacli/sample_outputs.py) are outputs from a real ssacli run. We don't yet have real samples for not OK status though.

2023-06-23 13:22 UTC, rgildein commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
Can you provide an example how metrics will look like?

2023-06-26 03:01 UTC, sudeephb commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
```
ssacli_ld_info{drive_id="1",slot="2",status="OK"} 1.0
```

2023-06-26 08:29 UTC, Pjack commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
We have similiar discussion here.
https://github.com/canonical/charm-prometheus-hardware-exporter/pull/10
The final conclusion is  ` == 1` is more precise compared to `> 0`

2023-06-26 08:36 UTC, Pjack requested changes
Overall, LTGM, 
Just a small thing that I want to confirm it again.

2023-06-26 08:42 UTC, sudeephb commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
I have updated the alert condition

2023-06-27 02:37 UTC, jneo8 approved these changes
LGTM

2023-06-27 02:42 UTC, jneo8 requested changes
Please address the name of metrics is same as in [Add collector for ssacli #12 ](https://github.com/canonical/prometheus-hardware-exporter/pull/12/files)

2023-06-27 02:51 UTC, jneo8 approved these changes
Nice and LGTM.

2023-06-27 04:28 UTC, Pjack approved these changes
LGTM

2023-06-27 05:25 UTC, merged

2023-07-04 13:10 UTC, rgildein commented on src/prometheus_alert_rules/ssacli.yaml
> +    expr: ssacli_ld_info{status != "OK"} > 0
My point was if we even have `ssacli_logical_drive_info{drive_id="1",slot="2",status="OK"} 0.0`. If yes, I think we should remove it, because it does not bring any more value and it only takes resources.