feat: hardware-verifier
canonical/charm-prometheus-hardware-exporter pull request #18
Opened 2023-06-27 08:45 UTC by jneo8

- hardware-verifier for
  - perccli
  - sas2ircu
  - sas3ircu
  - storcli
  - megacli
- Refactor VendorXXX to HWToolXXX
- Refactor the config of hardware to use Enum instead of string.

2023-06-28 05:16 UTC, Pjack requested changes

2023-06-28 05:16 UTC, Pjack commented on src/hw_tools.py
> +        if hw_info.get("vendor") == "Dell Inc":
I suggest this function is only used to verify if we can use storcli in this server. So, it's possible StorCLIStrategy.hw_verifier and PercCLIStrategy.hw_verifier are both return true.

We can put the installation strategy in upper layer.
Option 1: install both tool
Option 2: there is precedence, so only install 1 tool.
It helps us to modify the strategy easilar in the future.

2023-06-28 05:16 UTC, Pjack commented on src/hw_tools.py
> +            if info.get("id") == "raid" and info.get("product") in SUPPORT_STORAGES[self.name]:
fuzzy match
```suggestion
            if info.get("id") == "raid" and SUPPORT_STORAGES[self.name] in info.get("product"):
```

2023-06-28 05:16 UTC, Pjack commented on src/hw_tools.py
> +            if info.get("id") == "sas" and info.get("product") in SUPPORT_STORAGES[self.name]:
```suggestion
            if info.get("id") == "sas" and SUPPORT_STORAGES[self.name] in info.get("product"):
```

2023-06-28 05:16 UTC, Pjack commented on src/hw_tools.py
> +            if info.get("id") == "sas" and info.get("product") in SUPPORT_STORAGES[self.name]:
```suggestion
            if info.get("id") == "sas" and SUPPORT_STORAGES[self.name] in info.get("product"):
```

2023-06-28 05:16 UTC, Pjack commented on src/hw_tools.py
> +        for name in HW_TOOLS:
* Put our installation strategy here, make it implicit if there is any preference.
Option 1: install both
Option 2: some preference, e.g. storecli/perccli , pick 1

* there is no `break` after we install the tools, therefore, we may install multiple tools here.

2023-06-28 05:25 UTC, Pjack requested changes

2023-06-28 05:25 UTC, Pjack commented on src/hardware.py
> +        "SAS2308 PCI-Express Fusion-MPT SAS-2",
```suggestion
        "SAS2308",
```

2023-06-28 06:18 UTC, jneo8 commented on src/hw_tools.py
> +        for name in HW_TOOLS:
The break is not here because it's possible we have multiple different controllers in the same machine.

2023-06-28 06:37 UTC, jneo8 commented on src/hw_tools.py
> +        if hw_info.get("vendor") == "Dell Inc":
I would like to keep conditional expression in this layer is because we can't avoid to have complex rules for checking. The upper layer expression will be too complex and maybe exclude the situation that the machine have multiple controllers.

2023-06-28 06:39 UTC, jneo8 commented on src/hw_tools.py
> +        for name in HW_TOOLS:
Break will crowd out the multiple controllers situation.

2023-06-28 06:42 UTC, jneo8 commented on src/hardware.py
> +        "MegaRAID 12GSAS/PCIe Secure SAS39xx",
The document don't mention all the actual output of `product`. I am afraid this will be too hasty.

2023-06-29 02:25 UTC, Pjack commented on src/hw_tools.py
>              if isinstance(strategy, APTStrategyABC):
will the strategy can be APTStrategy & TPRStrategy at the same time? 
If not, then this one should be `elif`

2023-06-29 02:38 UTC, chanchiwai-ray approved these changes

2023-06-29 02:38 UTC, chanchiwai-ray commented on src/hw_tools.py
> +    storage_info = lshw(class_filter="storage")
Non-blocking: is it possible to get all the necessary information with only one `lshw()` called?

2023-06-29 02:38 UTC, chanchiwai-ray commented on src/hw_tools.py
> +                any(
Non-blocking question: can we do ?
```python3
if product in SUPPORT_STORAGES[HWTool.SAS3IRCU] and vendor == StorageVendor.BROADCOM:
    ...
```
Similarly, for the codes below

2023-06-29 02:38 UTC, chanchiwai-ray commented on src/hardware.py
> +    cmd = "sudo lshw -json"
Non-blocking: do we really need `sudo`? I thought charm codes are running with `root`. Adding `sudo` may cause issue in unit test if the test is not mocked correctly.

2023-06-29 02:41 UTC, jneo8 commented on src/hw_tools.py
> +        ]
It's not need anymore because we use the dict to register mapping between resource and strategy in previous proposal. But the mapping is move to config `TPR_RESOURCES`.

2023-06-29 02:45 UTC, jneo8 commented on src/hw_tools.py
> +    storage_info = lshw(class_filter="storage")
Yes we can. But the output will be very different any we need more parse logic for it.

2023-06-29 02:46 UTC, jneo8 commented on src/hw_tools.py
> +                any(
No we can't because it's fuzzy matching.

2023-06-29 02:47 UTC, jneo8 commented on src/hardware.py
> +    cmd = "sudo lshw -json"
We should mock it always.
But you are right we can remove sudo here.

2023-06-29 03:14 UTC, chanchiwai-ray commented on src/hw_tools.py
> +                any(
Ah, `product` is a list ?

2023-06-29 03:31 UTC, jneo8 commented on src/hw_tools.py
> +                any(
`SUPPORT_STORAGES[HWTool.SAS3IRCU]` will return list of fuzzy matching string.

It's same to:

```python
any(
_product for _product in ["SAS001", "SAS002"] if _product in "RAID Product info SAS001"
)
```

2023-06-29 04:14 UTC, sudeephb reviewed
Overall LGTM.
Left one non-blocking suggestion.

2023-06-29 04:14 UTC, sudeephb commented on src/hardware.py
> +SUPPORT_STORAGES = {
Non-blocking
```suggestion
SUPPORTED_STORAGES = {
```

2023-06-29 04:40 UTC, Pjack requested changes

2023-06-29 04:40 UTC, Pjack commented on src/hw_tools.py
> +                strategy.install()  # pylint: disable=E1120
Small thing... what about `else` ?  raise exception?

2023-06-29 04:59 UTC, jneo8 commented on src/hw_tools.py
> +                strategy.install()  # pylint: disable=E1120
It will just continue to next.
I won't use else because there is no default strategy.

2023-06-29 06:03 UTC, jneo8 commented on src/hardware.py
> +SUPPORT_STORAGES = {
updated

2023-06-29 06:30 UTC, sudeephb approved these changes

2023-06-29 07:55 UTC, Pjack commented on src/hw_tools.py
> +                strategy.install()  # pylint: disable=E1120
I think at least we should print out log or raise exception.
But it is a cornor case, I can close it first.

2023-06-29 07:55 UTC, Pjack approved these changes

2023-06-29 08:24 UTC, merged