test(tests): Add basic functional test for build & deploy
canonical/charm-prometheus-hardware-exporter pull request #4
Opened 2023-06-05 05:50 UTC by jneo8

2023-06-05 06:29 UTC, rgildein reviewed
One suggestion and two not-blocking comments, otherwise it's LGTM.

2023-06-05 06:29 UTC, rgildein commented on .github/workflows/pr.yaml
> +      commands: "['FUNC_ARGS=\"\" make functional']"
not-blocking: 
```suggestion
      commands: "['make functional']"
```

2023-06-05 06:29 UTC, rgildein commented on tests/functional/test_charm.py
> +    await ops_test.model.add_relation("ubuntu:juju-info", f"{APP_NAME}:general-info"),
```suggestion
    await ops_test.model.add_relation(f"{PRINCIPAL_APP_NAME}:juju-info", f"{APP_NAME}:general-info"),
```

2023-06-05 06:29 UTC, rgildein commented on .github/workflows/pr.yaml
> +      commands: "['FUNC_ARGS=\"\" make functional']"
not-blocking: However I'll suggest to add support for `--series` option for testing. It's easy to add and it helps, see example in [here](https://github.com/canonical/charm-simple-streams/blob/main/tests/functional/conftest.py).

2023-06-07 08:09 UTC, jneo8 commented on .github/workflows/pr.yaml
> +      commands: "['FUNC_ARGS=\"\" make functional']"
updated.

2023-06-07 08:09 UTC, jneo8 commented on tests/functional/test_charm.py
> +    await ops_test.model.add_relation("ubuntu:juju-info", f"{APP_NAME}:general-info"),
Updated.

2023-06-07 11:50 UTC, rgildein approved these changes
LGTM

2023-06-12 02:29 UTC, Pjack requested changes

2023-06-12 02:29 UTC, Pjack commented on tests/functional/requirements.txt
> +juju < 3
Will we use any juju library? I would like to avoid the dependency if possible. If there is any unavoidable dependency, please write some comment to indicate "when we can remove the limitation"

2023-06-12 04:16 UTC, jneo8 commented on tests/functional/requirements.txt
> +juju < 3
It's because we use `OpsTest` for functional test, and `juju` is it's dependency. If we do not provide this line, it will install the newest version of juju and it is not workable with controller < 3.
So it can only be removed if we upgrade our juju to 3.

2023-06-12 04:20 UTC, jneo8 commented on tests/functional/requirements.txt
> +juju < 3
Hi @Pjack do you think this comment make sense to you in requirement.txt?
`Make OpsTest works with controller version < 3`

2023-06-13 07:03 UTC, jneo8 commented on tests/functional/requirements.txt
> +juju < 3
Updated

2023-06-13 09:32 UTC, esunar approved these changes

2023-06-14 04:54 UTC, Pjack approved these changes
LGTM

2023-06-14 05:17 UTC, merged