Update alert rule for mega raid collector.
canonical/charm-prometheus-hardware-exporter pull request #9
Opened 2023-06-14 10:18 UTC by chanchiwai-ray

Update alert rule for MegaRAID collector according to the [PR](https://github.com/canonical/prometheus-hardware-exporter/pull/6)

Depends: [PR](https://github.com/canonical/prometheus-hardware-exporter/pull/6)

2023-06-15 02:38 UTC, jneo8 approved these changes

2023-06-15 10:33 UTC, Pjack requested changes

2023-06-15 10:33 UTC, Pjack commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
Question: when there are 2 virtual drive failed, how many alert will be sent out?  

I am thinking should we send the alert one by one, or should we send the alerts together. eg: check the value of megaraid_unready_virtual_drives  

if it is > 0 , then send alert.  

At the mean time, I still want to get the information that can indicate which virtual drives are unready.

2023-06-15 10:33 UTC, Pjack commented on src/prometheus_alert_rules/mega_raid.yaml
>        severity: critical
I feel it won't be critical. 
For example: For RAID 1, if it is not Optl, it means at least one of the physical drive is unavailable. But It won't imact the data access in general case.

2023-06-16 05:56 UTC, chanchiwai-ray commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
Answer: 2 alerts.

For second question. It maybe impossible if we use `megaraid_unready_virtual_drives` because there are no information about what virtual drives are unready in the label, and we cannot add these information in the label. So we cannot get what the number of unready virtual drive and what virtual drive are unready using single metrics.

2023-06-16 05:57 UTC, chanchiwai-ray commented on src/prometheus_alert_rules/mega_raid.yaml
>        severity: critical
ACK

2023-06-16 07:12 UTC, Pjack commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
Okay, let's design it as is but collect feedback during demo

2023-06-16 07:20 UTC, Pjack requested changes

2023-06-16 07:20 UTC, Pjack commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
@jneo8 mentioned this alert should be >=0
https://github.com/canonical/charm-prometheus-hardware-exporter/pull/10/files#diff-5be74e108dda67ee9e3c2a3354886eb79a213d34919599477befd19c71e98a16
Which one is correct?

2023-06-16 07:56 UTC, chanchiwai-ray commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
`>= 1` you mean? Larger than or equal to 1 is okay because we will not have value larger than 1

2023-06-16 09:20 UTC, jneo8 commented on src/prometheus_alert_rules/mega_raid.yaml
> +    expr: megaraid_virtual_drive_info{state != "Optl"} == 1
I think I am the wrong one.

So no matter 1 or 2 virtual drives' state is not Optl. It will fire the alert.

2023-06-16 09:27 UTC, Pjack approved these changes

2023-06-16 09:53 UTC, merged